CREATE TABLE personne (Nom varchar(255) NOT NULL, Prenom varchar(255) NOT NULL, estAdulte bit NOT NULL, inviteVin bit NOT NULL, inviteSoir bit NOT NULL, vientVin bit NOT NULL, vientSoir bit NOT NULL, id int GENERATED BY DEFAULT AS IDENTITY, mail varchar(255), responsableid int NOT NULL, PRIMARY KEY (id));
CREATE TABLE responsable (Nom varchar(255) NOT NULL, mdp varchar(255) NOT NULL, id int GENERATED BY DEFAULT AS IDENTITY, estAdmin bit DEFAULT 'false' NOT NULL, PRIMARY KEY (id));
ALTER TABLE personne ADD CONSTRAINT repondre FOREIGN KEY (responsableid) REFERENCES responsable (id);
