/*
 * Created on 19 nov. 2015 ( Time 13:31:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package cli.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "PERSONNE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="PERSONNE", schema="PUBLIC", catalog="MARIAGEAUDRENCYRIL" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PersonneEntity.countAll", query="SELECT COUNT(x) FROM PersonneEntity x" ),
  @NamedQuery ( name="PersonneEntity.ordered", query="SELECT x FROM PersonneEntity x order by x.responsable" )

} )
public class PersonneEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", nullable=false, length=255)
    private String     nom          ;

    @Column(name="PRENOM", nullable=false, length=255)
    private String     prenom       ;

    @Column(name="ESTADULTE", nullable=false)
    private Boolean    estadulte    ;

    @Column(name="INVITEVIN", nullable=false)
    private Boolean    invitevin    ;

    @Column(name="INVITESOIR", nullable=false)
    private Boolean    invitesoir   ;

    @Column(name="VIENTVIN", nullable=false)
    private Boolean    vientvin     ;

    @Column(name="VIENTSOIR", nullable=false)
    private Boolean    vientsoir    ;

    @Column(name="MAIL", length=255)
    private String     mail         ;

	// "responsableid" (column "RESPONSABLEID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="RESPONSABLEID", referencedColumnName="ID")
    private ResponsableEntity responsable ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PersonneEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : PRENOM ( VARCHAR ) 
    public void setPrenom( String prenom ) {
        this.prenom = prenom;
    }
    public String getPrenom() {
        return this.prenom;
    }

    //--- DATABASE MAPPING : ESTADULTE ( BOOLEAN ) 
    public void setEstadulte( Boolean estadulte ) {
        this.estadulte = estadulte;
    }
    public Boolean getEstadulte() {
        return this.estadulte;
    }

    //--- DATABASE MAPPING : INVITEVIN ( BOOLEAN ) 
    public void setInvitevin( Boolean invitevin ) {
        this.invitevin = invitevin;
    }
    public Boolean getInvitevin() {
        return this.invitevin;
    }

    //--- DATABASE MAPPING : INVITESOIR ( BOOLEAN ) 
    public void setInvitesoir( Boolean invitesoir ) {
        this.invitesoir = invitesoir;
    }
    public Boolean getInvitesoir() {
        return this.invitesoir;
    }

    //--- DATABASE MAPPING : VIENTVIN ( BOOLEAN ) 
    public void setVientvin( Boolean vientvin ) {
        this.vientvin = vientvin;
    }
    public Boolean getVientvin() {
        return this.vientvin;
    }

    //--- DATABASE MAPPING : VIENTSOIT ( BOOLEAN ) 
    public void setVientsoir( Boolean vientsoit ) {
        this.vientsoir = vientsoit;
    }
    public Boolean getVientsoir() {
        return this.vientsoir;
    }

    //--- DATABASE MAPPING : MAIL ( VARCHAR ) 
    public void setMail( String mail ) {
        this.mail = mail;
    }
    public String getMail() {
        return this.mail;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setResponsable( ResponsableEntity responsable ) {
        this.responsable = responsable;
    }
    public ResponsableEntity getResponsable() {
        return this.responsable;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nom);
        sb.append("|");
        sb.append(prenom);
        sb.append("|");
        sb.append(estadulte);
        sb.append("|");
        sb.append(invitevin);
        sb.append("|");
        sb.append(invitesoir);
        sb.append("|");
        sb.append(vientvin);
        sb.append("|");
        sb.append(vientsoir);
        sb.append("|");
        sb.append(mail);
        return sb.toString(); 
    } 
    
    public boolean equals(PersonneEntity personne){
    	return this.id.equals(personne.getId());
    }

}
