/*
 * Created on 19 nov. 2015 ( Time 13:31:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package cli.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import cli.bean.jpa.PersonneEntity;
import cli.persistence.commons.jpa.GenericJpaService;
import cli.persistence.commons.jpa.JpaOperation;
import cli.persistence.services.PersonnePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Personne" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PersonnePersistenceJPA extends GenericJpaService<PersonneEntity, Integer> implements PersonnePersistence {

	/**
	 * Constructor
	 */
	public PersonnePersistenceJPA() {
		super(PersonneEntity.class);
	}

	@Override
	public PersonneEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(PersonneEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("PersonneEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
