/*
 * Created on 19 nov. 2015 ( Time 13:31:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package cli.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import cli.bean.jpa.ResponsableEntity;
import cli.persistence.commons.jpa.GenericJpaService;
import cli.persistence.commons.jpa.JpaOperation;
import cli.persistence.services.ResponsablePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Responsable" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ResponsablePersistenceJPA extends GenericJpaService<ResponsableEntity, Integer> implements ResponsablePersistence {

	/**
	 * Constructor
	 */
	public ResponsablePersistenceJPA() {
		super(ResponsableEntity.class);
	}

	@Override
	public ResponsableEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(ResponsableEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("ResponsableEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
